version: '3.5'

services:
  watcher:
    image: ${APP_IMG}
    ports:
      - ${HTTP_PORT}:8080
    environment:
      TZ: "Europe/Moscow"
      WATCHER_TELEGRAM_CHATID:
    secrets: 
      - npulse_telegram_token
    volumes:
      - app_log:/app_n/log
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.hostname==${NODE_HOSTNAME}"

secrets:  
  npulse_telegram_token:
    external: true

volumes:
  app_log:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_DATA_SERVER},rw
      device: ":/srv/nfs/srvSwarmData/npulse-watcher/log"
